# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prefix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prefix
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Database'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'CodableFirebase'

  target 'PrefixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrefixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
