# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prefix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prefix
  pod 'Firebase/Core'

  target 'PrefixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrefixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
